//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("canwell - IT Solutions")]
[assembly: AssemblyVersion("3.9.71.2")]
[assembly: AssemblyFileVersion("3.9.71.2")]
[assembly: AssemblyInformationalVersion("3.9.71.2")]
[assembly: AssemblyCopyright("Copyright ©  2016")]

